name: CI production

on:
  # Triggers the workflow on pull request events but only for the production branch
  pull_request:
    types: [ closed ]
    branches:
    - 'production'

jobs:
  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      - uses: actions/checkout@v2
      - name: Deploy to Production
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
              ARGS: "--exclude /bootstrap/ --exclude /config/ --exclude /languages/"
              SOURCE: "www/application/"
              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}
              TARGET: ${{ secrets.TARGET }}
              EXCLUDE: ""